#include "macros.h"

#if CV_VERSION_GREATER_EQUAL(3, 2, 0)

#include <opencv2/opencv_modules.hpp>

#else
// OpenCV < 3.2.0 does not contain opencv_modules.hpp,
// thus we include the modules based on which libraries
// are found in OPENCV_LIB_DIR
#ifdef OPENCV4NODEJS_FOUND_MODULE_CALIB3D
#define HAVE_OPENCV_CALIB3D
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_DNN
#define HAVE_OPENCV_DNN
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_FACE
#define HAVE_OPENCV_FACE
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_FEATURES2D
#define HAVE_OPENCV_FEATURES2D
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_IMGPROC
#define HAVE_OPENCV_IMGPROC
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_HIGHGUI
#define HAVE_OPENCV_HIGHGUI
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_IMGCODECS
#define HAVE_OPENCV_IMGCODECS
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_VIDEOIO
#define HAVE_OPENCV_VIDEOIO
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_ML
#define HAVE_OPENCV_ML
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_OBJDETECT
#define HAVE_OPENCV_OBJDETECT
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_PHOTO
#define HAVE_OPENCV_PHOTO
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_TEXT
#define HAVE_OPENCV_TEXT
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_TRACKING
#define HAVE_OPENCV_TRACKING
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_VIDEO
#define HAVE_OPENCV_VIDEO
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_XFEATURES2D
#define HAVE_OPENCV_XFEATURES2D
#endif
#ifdef OPENCV4NODEJS_FOUND_MODULE_XIMGPROC
#define HAVE_OPENCV_XIMGPROC
#endif

#endif

#ifdef HAVE_OPENCV_HIGHGUI
#ifdef HAVE_OPENCV_IMGCODECS
#ifdef HAVE_OPENCV_VIDEOIO
#define HAVE_IO
#endif
#endif
#endif